
version: '3'
services:
  service1:
    image: image1
    environment:
      - ENV_VAR1=value1
    volumes:
      - /path/to/volume1:/path/in/container1
  service2:
    image: image2
    environment:
      - ENV_VAR2=value2
    volumes:
      - /path/to/volume2:/path/in/container2
    depends_on:
      - service1
