
version: '3.3'
services:
  radarr:
    image: linuxserver/radarr
    volumes:
      - /home/chatgpt/htpc-download-box/config/radarr:/config
      - /home/chatgpt/htpc-download-box/movies:/movies
      - /home/chatgpt/htpc-download-box/downloads:/downloads
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - /home/chatgpt/htpc-download-box/config/sonarr:/config
      - /home/chatgpt/htpc-download-box/tv:/tv
      - /home/chatgpt/htpc-download-box/downloads:/downloads
  nginx:
    image: nginx
    volumes:
      - /home/chatgpt/htpc-download-box/config/nginx:/etc/nginx/conf.d
  organizr:
    image: organizr/organizr
    volumes:
      - /home/chatgpt/htpc-download-box/config/organizr:/config
